#!/usr/bin/env bash

execPath=$(pwd)
isDebugMode=false

# update syteam
sudo pacman -Syu --noconfirm

# Updates app/packages
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed spotify-launcher
sudo pacman -S --noconfirm --needed curl
sudo pacman -S --noconfirm --needed discord
sudo pacman -S --noconfirm --needed kitty 
sudo pacman -S --noconfirm --needed xclip
sudo pacman -S --noconfirm --needed maim 
sudo pacman -S --noconfirm --needed fastfetch
sudo pacman -S --noconfirm --needed qutebrowser  
sudo pacman -S --noconfirm --needed noto-fonts-emoji  
sudo pacman -S --noconfirm --needed eza 

# uppdate dotfiles

cd $HOME/.dev/.dotfiles
git pull origin main

stow -D -t $HOME .

if [ "$isDebugMode" = true ] ; then
	eza -a 
fi
stow -t $HOME ./

cd "$execPath"
