#!/usr/bin/env bash

execPath=$(pwd)

# update syteam
sudo pacman -Syu --noconfirm

# Updates app/packages
sudo pacman -S -noconfirm --needed git curl

# uppdate dotfiles

cd $HOME/dev/.dotfiles
git pull origin main

stow -t $HOME .

cd "$execPath"
